name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar AWS CLI e Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Criar pacote da Lambda
        run: |
          cd lambda
          zip -r ../video_processor.zip .
          cd ..

      - name: Enviar para S3
        run: |
          aws s3 cp video_processor.zip s3://${{ secrets.AWS_S3_NAME }}/

      - name: Deploy com Terraform
        run: |
          terraform init
          terraform apply -auto-approve
