name: Deploy Lambda

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar AWS CLI e Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip

      - name: Configurar AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Criar pacote da Lambda
        run: |
          cd lambda
          zip -r ../video_processor.zip .
          cd ..

      - name: Enviar para S3
        env:
          AWS_S3_NAME: ${{secrets.AWS_S3_NAME}}
        run: aws s3 cp video_processor.zip s3://$AWS_S3_NAME/

      - name: Deploy com Terraform
        run: |
          terraform init
          terraform apply -auto-approve
